---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# modtrees

```mermaid
graph TD
    Pkg["modtrees"] --> R["R/"]
    Pkg --> Tests["tests/"]
    Pkg --> Desc["DESCRIPTION"]
    Pkg --> Ns["NAMESPACE"]
    R --> ModTree["mod_tree.R"]
    R --> Extract["extract_func_def.R"]
    R --> UsesNs["uses_ns.R"]
    R --> FindCalls["find_calls.R"]
    R --> BuildTree["build_tree.R"]
    R --> RenderTree["render_tree.R"]
    Tests --> TH["testthat.R"]
    Tests --> TDir["testthat/"]
    TDir --> T1["test-extract_func_def.R"]
    TDir --> T2["test-uses_ns.R"]
    TDir --> T3["test-find_calls.R"]
    TDir --> T4["test-build_tree.R"]
    TDir --> T5["test-render_tree.R"]
    TDir --> T6["test-mod_tree.R"]
```

<!-- badges: start -->
<!-- badges: end -->

The goal of `modtrees` is to create plain-text tree views of module and namespace hierarchy by statically parsing R source files.

## Installation

You can install the development version of `modtrees` like so:

``` r
install.packages("remotes")
remotes::install_github("mjfrigaard/modtrees")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(modtrees)
## basic example code
```
